### PR TITLE
Remove Symfony 4.2 deprecation

### PR DESCRIPTION
**Pull request by jildertmiedema**

### CODE REVIEW

**Comment by tabbi89** [comment]
Ping :P

**Comment by rosstuck** [comment]
I appreciate the pings and approves, fellas, but this PR has failing tests. If you'd like it merged faster, then that would be more help.

One of them looks like a quick change to travis.yml to exclude 7.0+Symfony 4.2 from the build matrix (good starter issue @tabbi89?)

The other ones are in the SecurityVoter tests, not sure what's up with that? Did that component change in the 4.2 release? The test failure messages aren't super helpful, unfortunately. :-/ https://travis-ci.org/thephpleague/tactician-bundle/jobs/464385869

**Comment by chalasr** [comment]
Failing tests are fixed by #109 (precisely https://github.com/thephpleague/tactician-bundle/pull/109/commits/002482c26a72f81ef0120bf461f9712ba8f3d8c5), merging it should unlock this one

**Comment by PabloKowalczyk** [comment]
@chalasr after #109 merge there will be no changes in this PR :)

**Comment by rosstuck** [comment]
Closed in favor of #109. Sorry @jildertmiedema, I appreciate the work though and next time I see you, drinks are on me. :)

**Pull request closed without merging**
