### PR TITLE
Fixes #90 - Ignore interface typehinted functions

### LINKED ISSUE #90: Typehint mapping and setter injection
I have a question/issue about/with Typehint mapping and setter injection.

I implement an interface on all of my handler classes:

```
    _instanceof:
        AppBundle\Service\HandlerInterface:
            tags:
                - { name: tactician.handler, typehints: false }
            autowire: true
            public: true
```

All goes fine by this.

But one handler requires a setter injection, for example.

```
    /**
     * @param EntityManagerInterface $em
     *
     * @required
     */
    public function setEm(EntityManagerInterface $em): void
    {
        $this->em = $em;
    }
```

The problem here is that the `findCommandsForService` in `TypeHintMapping` will find this function and tries to map it.
This will trigger the following error:

```
Can not route Doctrine\ORM\EntityManagerInterface to AppBundle\Service\Membership\MembershipRegistrationHandler, class Doctrine\ORM\EntityManagerInterface does not exist!
```

Because of

```
if (!class_exists($commandClassName)) {
    throw new InvalidArgumentException("Can not route $commandClassName to $serviceId, class $commandClassName does not exist!");
}
```

I could create a custom mapping, which only checks for a `handle` function instead of all other function in my class. But is this the expected behaviour? Or should we filter out functions with interface typehinting?

Thanks!

### PR DESCRIPTION
**Pull request by jverdeyen**

### CODE REVIEW

**Comment by rosstuck** [comment]
Looking good! Don't sweat the build failures, being dealt with in #92. :)

**Comment by rosstuck** [comment]
Er, #91. ;-)

**Comment by rosstuck** [comment]
I trust your tests are failing due to Symfony 4 stuff, not the new check 😆 

Thanks a ton for picking this up and for the quick action, I'll tag a new release with this included later this week.

**Comment by jverdeyen** [comment]
You're welcome. Thanks for your effort in this bundle!
I'll use dev-master for now. Thanks @rosstuck !

**Pull request merged**
