### PR TITLE
Fix test suite errors on symfony4

### PR DESCRIPTION
**Pull request by rosstuck**
Noticed this started kicking in once Symfony4 was released. This isn't really elegant but it's the best I've got off the top of my head.

Any thoughts, @chalasr?

### CODE REVIEW

**Comment by rosstuck** [comment]
Also started updating Travis config https://github.com/thephpleague/tactician-bundle/commit/13785c4e84171c35d8585c22a50eeabe54fd3f1f

**Comment by rosstuck** [comment]
If there are no objections, I'll merge this tonight and tag a new release.

**Comment by tyx** [comment]
It's fine for me to make command bus public :+1:

**Comment by chalasr** [comment]
Same 👍 Sorry for the late answer.

**Comment by rosstuck** [comment]
No worries, I appreciate you both taking the time! ❤️

**Pull request merged**
