### PR TITLE
Allow tagging handlers per bus

### PR DESCRIPTION
**Pull request by tyx**
Following #20

Just let the check of `tactician.middleware.command_handler` as I'm not sure to get what is wrong with it.

Let me know what we need to go forward.

### CODE REVIEW

**Comment by tyx** [comment]
ping @rosstuck

**Comment by rosstuck** [comment]
Trying to make time, laid low with stomach flu, work and conf org. I'll get to it Saturday at the latest, really sorry. :(

**Comment by tyx** [comment]
Oh ! Take care of yourself, no problem ;) 

I will start to use my fork for now.

**Comment by rosstuck** [comment]
Okay, made another review and tried to dive back into this code (the bundle was never really my work in the first place :smile:).

First off, the bad news: I've made your job slightly harder by merging another PR that's been pending a while and adds a new security middleware. I'm felt it should go first but I am sorry about that.

Good news: if you can add docs for the multi-bus features, I'll merge it. I still need to complete a test with the security features before tagging a release but we'll be one step closer.

Regarding the big issue in the old PR, if dynamic command handler middleware names are a good idea, I'm not sure there's any good fix so let's write good docs there and ship it. 

Sorry for the extra hassle, it's not fair to you and I really appreciate your effort!

**Comment by tyx** [comment]
no problem, as we say in french : "c'est le jeu ma pauvre lucette" ! ;)

**Comment by tyx** [comment]
I'm back on this PR !

I just rebased and add some doc. Let me know if it's enough or if I miss anything else.

**Comment by rosstuck** [comment]
Broken build aside, looks pretty good to me. The build failure looks like this: https://github.com/sebastianbergmann/phpunit/issues/2015

I'm going to ping @rdohms and @boekkooi because they had some input on the initial version. I'm organizing DomCode this week so my availability will....vary. :sweat_smile:

**Comment by tyx** [comment]
Hi,

hope we can move forward on this issue soon if you get some extra time !

**Comment by tyx** [comment]
Thanks @rosstuck \o/

I guess we can plan to tag a new release (0.5 regarding the new feature security) : https://github.com/thephpleague/tactician-bundle/compare/v0.4.1...master what do you think ? No hurry, I can rely to the dev-master on my side, but I like tag :p

**Comment by rosstuck** [comment]
Well, that was the plan after fixing the build last night but then I started running into #31 on a fresh install. Sooooo now I've got to try and fix those issues this weekend maybe? I don't feel right tagging a release where the config from the readme immediately results in implementation errors with no useful debugging messages for the user.

In the meantime, dev-master is easier than your own fork at least so small steps forward? :sweat_smile:

**Pull request merged**
