### PR TITLE
Start updating test suite

### PR DESCRIPTION
**Pull request by rosstuck**
- Drop support for under PHP 7
- Move to PHPUnit 6
- Update travis matrix
- Fix broken unit tests about validator not being enabled
- Split integration tests into base class and refactor a bit
- Some various cleanup

### CODE REVIEW

**Comment by rosstuck** [comment]
@tyx @RonRademaker I've fixed the broken build and started looking at what it would take to update the test suite a bit. There's a new issue involving PHPUnit 6 and old versions of Symfony ( https://travis-ci.org/thephpleague/tactician-bundle/jobs/229714117 ). If you know of a quick fix, let me know.

This is as far as I can go at the moment but I'll keep chasing this through the week.

**Comment by RonRademaker** [comment]
The only quick fix I can think of is adding a `PHPUnit_Framework_TestCase` that is just an empty extend to fix this incompatibility.

However, I think that symfony version just is and won't be compatible with PHPUnit 6, so perhaps phpunit 6 is not a viable option yet? PHPUnit 5 should work.

**Comment by tyx** [comment]
I should admit I don't use phpunit in general, so no idea for now. But I'm pretty sure I read a lot a complaint about a change in phpunit and even Symfony [should release a quick fix](http://symfony.com/blog/symfony-3-2-6-released) through this PR https://github.com/symfony/symfony/pull/21946

May be you can find a solution in comments?

**Comment by tyx** [comment]
Greeeeeeen :tada:

**Comment by RonRademaker** [comment]
🎉  🍾

**Comment by rosstuck** [comment]
Yup, progress! I'm going through the rest of the test suite right now. There's some gaps in here that we really need to resolve (for example, the Mockery test listener wasn't enabled and adding Mockery::close to some tests cause them to fail *GULP*).

Expect more pushes after I cook lunch. :)

**Comment by rosstuck** [comment]
This is as far as I can go today, I'll pick it up again a bit tomorrow.

I'd like to simplify the way the Extension and CommandHandler pass work next. I'm playing with the idea of creating some "BusConfig" value objects that the Extension loads in and the compiler pass reads in as a private service. We could offload some of the logic into these VOs and make the whole thing a lot more testable/easy to main...at least, that's the idea. Not sure if it'll work yet.

On the flip side, we now have an IntegrationTest base class. If anyone's feeling feisty, I could use some help with writing integration tests for things like the security component, validator or doctrine bridges.

**Comment by mvrhov** [comment]
Hm... Aren't     "matthiasnoback/symfony-config-test": "^3.0", "matthiasnoback/symfony-dependency-injection-test": "^2.1" only needed for testing.. 
If yes, then they should be in requre-dev section.

**Comment by rosstuck** [comment]
Sounds legit. I'm on vacation right now but if you'll send a separate PR
moving them, I'm happy to merge it. :)

On Jul 16, 2017 10:25 PM, "Miha Vrhovnik" <notifications@github.com> wrote:

Hm... Aren't "matthiasnoback/symfony-config-test": "^3.0",
"matthiasnoback/symfony-dependency-injection-test": "^2.1" only needed for
testing..
If yes, then they should be in requre-dev section.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/tactician-bundle/pull/41#issuecomment-315634712>,
or mute the thread

**Pull request merged**
