### PR TITLE
Added Symfony3 compatibility

### PR DESCRIPTION
**Pull request by gnugat**
I've checked the bundle's tests against Symfony3 and all it needed to pass was escaping service IDs in YAML configuration (`@` is a YAML, reserved for future use).

Note that it's not a full guarantee that the bundle would work in a Symfony 3 application (maybe the tests miss something), but that's a good start :) .

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

**Comment by rosstuck** [comment]
Hi @gnugat! Thanks for getting on this issue early, I really appreciate it. If there's any other Symfony3 issues, please let me know. :)

**Comment by gnugat** [comment]
No worries, I'll keep an eye on it (should be fine though, given the minimalistic usage of Symfony's APIs).
Thanks for the amazing lib!

**Comment by rosstuck** [comment]
you rock

**Pull request merged**
