### PR TITLE
Trying to fix Travis builds

### PR DESCRIPTION
**Pull request by gnugat**
First try.

Have a look at PR #14

### CODE REVIEW

**Comment by gnugat** [comment]
@rosstuck: All builds pass.

Please note that I've branched off `master` and that the PR would be merged into `master`.

**Comment by rosstuck** [comment]
Merged and a new release tagged. Thanks a ton! :smile:

**Comment by gnugat** [comment]
Merci bucket :smile:

**Comment by WouterJ** [comment]
:+1: Thanks @gnugat & @rosstuck for your quick reaction following the Sf 3 release!

**Comment by gnugat** [comment]
What would be Symfony 3 without Tactician? :wink:

**Pull request merged**
