### PR TITLE
Allow league/tactician-container v3

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by PabloKowalczyk** [comment]
Hey @rosstuck, any update on this?

**Comment by TrafeX** [comment]
This change is required to make the bundle compatible with Symfony 6.x.

Composer will conflict with tactician-container 2.0:

```
Problem 1
    - league/tactician-bundle v1.3.2 requires league/tactician-container ^2.0 -> satisfiable by league/tactician-container[2.0.0].
    - league/tactician-bundle v1.3.1 requires league/tactician-logger ^0.10.0 -> satisfiable by league/tactician-logger[v0.10.0].
    - league/tactician-bundle v1.3.0 requires symfony/config ^3.4|^4.4|^5.0 -> found symfony/config[v3.4.0, ..., v3.4.47, v4.4.0, ..., v4.4.42, v5.0.0, ..., v5.4.9] but the package is fixed to v6.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/tactician-container 2.0.0 requires psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/tactician-logger v0.10.0 requires psr/log ~1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires league/tactician-bundle ^1.3 -> satisfiable by league/tactician-bundle[v1.3.0, v1.3.1, v1.3.2].
```
I've forked this repo and applied this patch which resolved the issue.

**Comment by PabloKowalczyk** [comment]
Is there any way to ping whole @thephpleague organization?

**Comment by frankdejonge** [comment]
@simPod merged and tagged as 1.4.0

**Comment by simPod** [comment]
@frankdejonge thank you. BTW do you need help with maintenance of tactician packages?

**Comment by frankdejonge** [comment]
@simPod in the long run it would be great to get help. I'm going to be taking over the maintenance for now. If there is a stable pattern of contributing, I'm open to expanding maintainers for this. So if that's interesting for you then let's work on that :)

**Comment by rosstuck** [comment]
Indeed, I've discussed with Frank and he'll be taking over for the
foreseeable future. He's got an amazing track record, he understands the
project very well, and we keep a short line with each other.

From my side, I'm not working in PHP or even as an IC anymore, and I just
don't have space for it (and haven't for quite some time). My apologies for
not being the best maintainer and the frustration that's caused y'all.

I think it would be great to reduce some of Frank's already substantial OSS
load, so I'm sure contributions would be very welcome but it's his show
from now on. 😘

**Comment by simPod** [comment]
Thanks for info guys. 🚀

**Comment by PabloKowalczyk** [comment]
@rosstuck no problem, thanks for all your work. I could also help with maintenance, just say a word :)

**Pull request merged**
