### PR TITLE
Remove PHP 8.1 deprecation

### PR DESCRIPTION
**Pull request by atomiix**

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by ruudk** [comment]
@atomiix Thanks for fixing this!

@rosstuck Anything holding back merging this PR? This would solve these errors on PHP 8.1 CI. It would be great to have this tagged. 🙏 
```
Return type of League\Tactician\Bundle\DependencyInjection\Compiler\BusBuilder\BusBuilders::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

**Comment by rosstuck** [comment]
I've merged this, switched the repo over to Github Actions for the build, and brought the minumum-stability back up from "beta" to dev so that Symfony 5.4 doesn't keep flunking the build (there's something up with the new security system).

If that still looks good with y'all, happy to tag a release tomorrow.

**Comment by chalasr** [comment]
@rosstuck looks good, thanks.
Just opened #128 which sets the minimum stability back to beta and makes the necessary changes to support Symfony 5.4 and 6.0.

**Comment by rosstuck** [comment]
Tagged in v1.3.1

**Pull request merged**
