### PR TITLE
Add support for logger middleware

### PR DESCRIPTION
**Pull request by tomaszhanc**
It would be nice to use Logger Middleware as well (`tactician.middleware.logger`). The dependency from Logger Middleware is not mandatory.

### CODE REVIEW

**Comment by rosstuck** [comment]
Sorry for the backlog on your PRs, been busy with workshops this week, I'll make some time in the next couple days to review everything. My apologies!

**Comment by rosstuck** [comment]
Looks pretty good, though it looks like we need to

a) broaden the test matrix to include logger as an actual dependency so we know it works
b) just add tactician-logger as a required dependency. All of our supported Symfony versions depend on psr/log so we're not adding any new dependencies for applications and this removes the additional complexity of conditional checks.

I'm in favor of option B since it's easier for maintenance and our builds take long enough, but if anyone has any other ideas, I'm open to suggestion. :)

**Comment by tyx** [comment]
I'm ok with the B as we already include tactician-logger in our apps and I feel that people who don't include it just don't know its existence

**Comment by rosstuck** [comment]
Okie dokies, let's do that. @tomaszhanc: Would you like to take this one further in that direction or are you backlogged for now? :)

**Comment by tomaszhanc** [comment]
@rosstuck sure, will do it :)

**Comment by tomaszhanc** [comment]
@rosstuck Sorry for a delay, it turned out December was a really busy month for me. Hope now we've got everything we need. If not, just let me know :)

**Comment by rosstuck** [comment]
No worries, swamped here as well. Looks good to me though, nice work and thanks for contributing! I'll tag a release with this soon-ish, after closing a few other issues.

Thanks again! :)

**Comment by rosstuck** [comment]
@tomaszhanc Oh, just a thought: once this is tagged for release, maybe it would be a good idea to add the logger to the symfony recipes template. :) 

https://github.com/symfony/recipes-contrib/blob/master/league/tactician-bundle/1.0/config/packages/league_tactician.yaml

Thanks again!

**Comment by tomaszhanc** [comment]
@rosstuck Sure, I'll do it. Before creating a new tag I would like to create a PR to register `ClassNameInflector` in DI container from https://github.com/thephpleague/tactician/pull/118

**Comment by rosstuck** [comment]
Sure, I'm waiting to see if we get any confirmation on the Symfony 3.4 issues before tagging a new release so there's no rush :)

**Comment by tomaszhanc** [comment]
Ahhh sorry it took me so long to finish it:

- https://github.com/thephpleague/tactician-bundle/pull/99
- https://github.com/symfony/recipes-contrib/pull/292

**Comment by rosstuck** [comment]
No worries, this is your free time and I appreciate you spending it on this at all. My apologies for taking so long to review and merge. :)

Great work and thanks for contributing!

**Pull request merged**
