### PR TITLE
Add test for ClassNameMapping

### PR DESCRIPTION
**Pull request by dmecke**
It took me quite a while to grasp how things work exactly, but eventually I managed to write a test for the ClassNameMapping. I ~borrowed~ stole much of the structure from the TypeHintMappingTest and adjusted it to the use case. I am not sure though, if everything is complete / meaningful. Please feel free to point me to right direction where necessary.

### CODE REVIEW

**Comment by rosstuck** [comment]
Hi @dmecke! Thanks for this PR, it looks really good. 😄

I'm sorry it was hard to figure out how it works, if you have any suggestions on how we can improve it, please let me know. 

Either way this helps move the main PR along so it's much appreciated. 👍

**Comment by dmecke** [comment]
Thanks!

I thinks it's just because of the need for a library to support many use cases and offer that much flexibility while app code mainly focuses on one (or only a few) use cases and therefore is much more concrete. I of course really appreciate that flexibility!

One idea could be to offer separate testsuites in the phpunit config for unit and integration tests.
I started off by searching for code without unit tests, but the integration tests fake the code coverage a bit in this case, so I excluded the integration tests to find code without unit tests.

**Comment by rosstuck** [comment]
Thanks for the feedback! If I ever get around to Tactician 2, I'm going to make it way less flexible and have folks focus on writing their own middleware instead. 😑 

I like the separate test suites idea, I've been doing this locally. Will take a peek at it today. Thanks again for the help!

**Comment by rosstuck** [comment]
Done: https://github.com/thephpleague/tactician-bundle/pull/67/commits/334eb4f364b3adc8c9c5393650a5dd556b4b0ebd

**Pull request merged**
