### PR TITLE
Improve support Symfony 7

### PR DESCRIPTION
**Pull request by olegpro**
```
!!  Fatal error: Declaration of League\Tactician\Bundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /app/vendor/league/tactician-bundle/src/DependencyInjection/Configuration.php on line 22
```

### CODE REVIEW

**Comment by wnnawalaniec** [comment]
I'm looking forward merging that pr

**Comment by olegpro** [comment]
@frankdejonge can we merge and releases?

**Comment by nexik** [comment]
Please accept this so we can move forward with upgrade of my project alternative is really doom :(

**Comment by frankdejonge** [comment]
It's released as 1.5.1

**Pull request merged**
