### PR TITLE
Remove PHP8 deprecation notices

### LINKED ISSUE #124: ReflectionParameter::getClass() is deprecated in PHP8
On PHP8 this method is deprecated

https://github.com/thephpleague/tactician-bundle/blob/66b97472915290b93654e60610295660f597ad4e/src/DependencyInjection/HandlerMapping/TypeHintMapping.php#L61

Not sure what's the best way to address it right now

### PR DESCRIPTION
**Pull request by acasademont**
And also:

- Bump minimum PHP to 7.2
- Bump PHPUnit to 8.5
- Remove unneeded Travis dependencies (although this should be probably moved to Github Actions)

fixes #124

### CODE REVIEW

**Comment by acasademont** [comment]
PS: I assumed handlers with PHP8 Union Types should not be registered. Let me know if you think otherwise @rosstuck , thx!!

**Comment by rosstuck** [comment]
Agreed on the union types, I feel like any handler that's receiving more than one command is probably doing something fishy, so let's not add to that.

Otherwise, thanks a ton for picking this up! I like the PR and it seems like you're transitioning everything nicely. The only thing I'd tweak is making this 1.3 since it drops earlier PHP version support.

Seems like just a few failing tests still and then I'm happy to merge and tag. Thanks once again! :heart:

**Comment by acasademont** [comment]
Yes, dealing with multiple symfony and phpunit versions can be a bit of a PITA. Plus Travis seems to take hours these days. Everything should be ready now :D

**Comment by rosstuck** [comment]
This is just a genuinely lovely PR, thank you so much for picking this up and handling it so well. Much :heart:, I really appreciate it. :smile:

**Comment by acasademont** [comment]
Thanks @rosstuck, my pleasure!

**Pull request merged**
